// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_api.proto

package BiuRpc_AppApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//城市类型
type SignCityType int32

const (
	SignCityType_CITY_TYPE_NONE     SignCityType = 0
	SignCityType_CITY_TYPE_PROVINCE SignCityType = 1
	SignCityType_CITY_TYPE_CITY     SignCityType = 2
	SignCityType_CITY_TYPE_DISTRICT SignCityType = 3
)

var SignCityType_name = map[int32]string{
	0: "CITY_TYPE_NONE",
	1: "CITY_TYPE_PROVINCE",
	2: "CITY_TYPE_CITY",
	3: "CITY_TYPE_DISTRICT",
}

var SignCityType_value = map[string]int32{
	"CITY_TYPE_NONE":     0,
	"CITY_TYPE_PROVINCE": 1,
	"CITY_TYPE_CITY":     2,
	"CITY_TYPE_DISTRICT": 3,
}

func (x SignCityType) String() string {
	return proto.EnumName(SignCityType_name, int32(x))
}

func (SignCityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{0}
}

//轮播
type Banner struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Nav                  *Nav     `protobuf:"bytes,3,opt,name=nav,proto3" json:"nav,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{0}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Banner) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Banner) GetNav() *Nav {
	if m != nil {
		return m.Nav
	}
	return nil
}

//@desc 获取版本列表
//@class Home
//@method GetHomeInfo
//请求服务端
type RequestHomeGetHomeInfo struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHomeGetHomeInfo) Reset()         { *m = RequestHomeGetHomeInfo{} }
func (m *RequestHomeGetHomeInfo) String() string { return proto.CompactTextString(m) }
func (*RequestHomeGetHomeInfo) ProtoMessage()    {}
func (*RequestHomeGetHomeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{1}
}

func (m *RequestHomeGetHomeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHomeGetHomeInfo.Unmarshal(m, b)
}
func (m *RequestHomeGetHomeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHomeGetHomeInfo.Marshal(b, m, deterministic)
}
func (m *RequestHomeGetHomeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHomeGetHomeInfo.Merge(m, src)
}
func (m *RequestHomeGetHomeInfo) XXX_Size() int {
	return xxx_messageInfo_RequestHomeGetHomeInfo.Size(m)
}
func (m *RequestHomeGetHomeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHomeGetHomeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHomeGetHomeInfo proto.InternalMessageInfo

func (m *RequestHomeGetHomeInfo) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

// 返回客户端
type ResponseHomeGetHomeInfo struct {
	Base                 *Response `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BannerList           []*Banner `protobuf:"bytes,2,rep,name=bannerList,proto3" json:"bannerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseHomeGetHomeInfo) Reset()         { *m = ResponseHomeGetHomeInfo{} }
func (m *ResponseHomeGetHomeInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseHomeGetHomeInfo) ProtoMessage()    {}
func (*ResponseHomeGetHomeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{2}
}

func (m *ResponseHomeGetHomeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHomeGetHomeInfo.Unmarshal(m, b)
}
func (m *ResponseHomeGetHomeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHomeGetHomeInfo.Marshal(b, m, deterministic)
}
func (m *ResponseHomeGetHomeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHomeGetHomeInfo.Merge(m, src)
}
func (m *ResponseHomeGetHomeInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseHomeGetHomeInfo.Size(m)
}
func (m *ResponseHomeGetHomeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHomeGetHomeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHomeGetHomeInfo proto.InternalMessageInfo

func (m *ResponseHomeGetHomeInfo) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseHomeGetHomeInfo) GetBannerList() []*Banner {
	if m != nil {
		return m.BannerList
	}
	return nil
}

//@desc 获取推荐商品列表
//@class Home
//@method GetRecommendProductList
//请求服务端
type RequestHomeGetRecommendProductList struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHomeGetRecommendProductList) Reset()         { *m = RequestHomeGetRecommendProductList{} }
func (m *RequestHomeGetRecommendProductList) String() string { return proto.CompactTextString(m) }
func (*RequestHomeGetRecommendProductList) ProtoMessage()    {}
func (*RequestHomeGetRecommendProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{3}
}

func (m *RequestHomeGetRecommendProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHomeGetRecommendProductList.Unmarshal(m, b)
}
func (m *RequestHomeGetRecommendProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHomeGetRecommendProductList.Marshal(b, m, deterministic)
}
func (m *RequestHomeGetRecommendProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHomeGetRecommendProductList.Merge(m, src)
}
func (m *RequestHomeGetRecommendProductList) XXX_Size() int {
	return xxx_messageInfo_RequestHomeGetRecommendProductList.Size(m)
}
func (m *RequestHomeGetRecommendProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHomeGetRecommendProductList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHomeGetRecommendProductList proto.InternalMessageInfo

func (m *RequestHomeGetRecommendProductList) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestHomeGetRecommendProductList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestHomeGetRecommendProductList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 返回客户端
type ResponseHomeGetRecommendProductList struct {
	Base                 *Response        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProductList          []*SimpleProduct `protobuf:"bytes,2,rep,name=productList,proto3" json:"productList,omitempty"`
	TotalPage            int32            `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResponseHomeGetRecommendProductList) Reset()         { *m = ResponseHomeGetRecommendProductList{} }
func (m *ResponseHomeGetRecommendProductList) String() string { return proto.CompactTextString(m) }
func (*ResponseHomeGetRecommendProductList) ProtoMessage()    {}
func (*ResponseHomeGetRecommendProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{4}
}

func (m *ResponseHomeGetRecommendProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHomeGetRecommendProductList.Unmarshal(m, b)
}
func (m *ResponseHomeGetRecommendProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHomeGetRecommendProductList.Marshal(b, m, deterministic)
}
func (m *ResponseHomeGetRecommendProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHomeGetRecommendProductList.Merge(m, src)
}
func (m *ResponseHomeGetRecommendProductList) XXX_Size() int {
	return xxx_messageInfo_ResponseHomeGetRecommendProductList.Size(m)
}
func (m *ResponseHomeGetRecommendProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHomeGetRecommendProductList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHomeGetRecommendProductList proto.InternalMessageInfo

func (m *ResponseHomeGetRecommendProductList) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseHomeGetRecommendProductList) GetProductList() []*SimpleProduct {
	if m != nil {
		return m.ProductList
	}
	return nil
}

func (m *ResponseHomeGetRecommendProductList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

//列表商品
type SimpleProduct struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover                *Picture `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleProduct) Reset()         { *m = SimpleProduct{} }
func (m *SimpleProduct) String() string { return proto.CompactTextString(m) }
func (*SimpleProduct) ProtoMessage()    {}
func (*SimpleProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{5}
}

func (m *SimpleProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleProduct.Unmarshal(m, b)
}
func (m *SimpleProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleProduct.Marshal(b, m, deterministic)
}
func (m *SimpleProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleProduct.Merge(m, src)
}
func (m *SimpleProduct) XXX_Size() int {
	return xxx_messageInfo_SimpleProduct.Size(m)
}
func (m *SimpleProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleProduct.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleProduct proto.InternalMessageInfo

func (m *SimpleProduct) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleProduct) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SimpleProduct) GetCover() *Picture {
	if m != nil {
		return m.Cover
	}
	return nil
}

func (m *SimpleProduct) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

//商品
type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover                *Picture `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{6}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetCover() *Picture {
	if m != nil {
		return m.Cover
	}
	return nil
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

//商品评价
type ProductComment struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *SimpleUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content              string      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           int32       `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProductComment) Reset()         { *m = ProductComment{} }
func (m *ProductComment) String() string { return proto.CompactTextString(m) }
func (*ProductComment) ProtoMessage()    {}
func (*ProductComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{7}
}

func (m *ProductComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductComment.Unmarshal(m, b)
}
func (m *ProductComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductComment.Marshal(b, m, deterministic)
}
func (m *ProductComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductComment.Merge(m, src)
}
func (m *ProductComment) XXX_Size() int {
	return xxx_messageInfo_ProductComment.Size(m)
}
func (m *ProductComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductComment.DiscardUnknown(m)
}

var xxx_messageInfo_ProductComment proto.InternalMessageInfo

func (m *ProductComment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductComment) GetUser() *SimpleUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ProductComment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ProductComment) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

//分类
type Category struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Level                int32       `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Sort                 int32       `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	CreateTime           int32       `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int32       `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CategoryList         []*Category `protobuf:"bytes,7,rep,name=categoryList,proto3" json:"categoryList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{8}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Category) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Category) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Category) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Category) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Category) GetCategoryList() []*Category {
	if m != nil {
		return m.CategoryList
	}
	return nil
}

//@desc 获取分类列表
//@class Product
//@method GetCategoryList
//请求服务端
type RequestProductGetCategoryList struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestProductGetCategoryList) Reset()         { *m = RequestProductGetCategoryList{} }
func (m *RequestProductGetCategoryList) String() string { return proto.CompactTextString(m) }
func (*RequestProductGetCategoryList) ProtoMessage()    {}
func (*RequestProductGetCategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{9}
}

func (m *RequestProductGetCategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestProductGetCategoryList.Unmarshal(m, b)
}
func (m *RequestProductGetCategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestProductGetCategoryList.Marshal(b, m, deterministic)
}
func (m *RequestProductGetCategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestProductGetCategoryList.Merge(m, src)
}
func (m *RequestProductGetCategoryList) XXX_Size() int {
	return xxx_messageInfo_RequestProductGetCategoryList.Size(m)
}
func (m *RequestProductGetCategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestProductGetCategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestProductGetCategoryList proto.InternalMessageInfo

func (m *RequestProductGetCategoryList) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

// 返回客户端
type ResponseProductGetCategoryList struct {
	Base                 *Response   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CategoryList         []*Category `protobuf:"bytes,2,rep,name=categoryList,proto3" json:"categoryList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseProductGetCategoryList) Reset()         { *m = ResponseProductGetCategoryList{} }
func (m *ResponseProductGetCategoryList) String() string { return proto.CompactTextString(m) }
func (*ResponseProductGetCategoryList) ProtoMessage()    {}
func (*ResponseProductGetCategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{10}
}

func (m *ResponseProductGetCategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseProductGetCategoryList.Unmarshal(m, b)
}
func (m *ResponseProductGetCategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseProductGetCategoryList.Marshal(b, m, deterministic)
}
func (m *ResponseProductGetCategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseProductGetCategoryList.Merge(m, src)
}
func (m *ResponseProductGetCategoryList) XXX_Size() int {
	return xxx_messageInfo_ResponseProductGetCategoryList.Size(m)
}
func (m *ResponseProductGetCategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseProductGetCategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseProductGetCategoryList proto.InternalMessageInfo

func (m *ResponseProductGetCategoryList) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseProductGetCategoryList) GetCategoryList() []*Category {
	if m != nil {
		return m.CategoryList
	}
	return nil
}

//@desc 获取商品列表
//@class Product
//@method GetProductList
//请求服务端
type RequestProductGetProductList struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestProductGetProductList) Reset()         { *m = RequestProductGetProductList{} }
func (m *RequestProductGetProductList) String() string { return proto.CompactTextString(m) }
func (*RequestProductGetProductList) ProtoMessage()    {}
func (*RequestProductGetProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{11}
}

func (m *RequestProductGetProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestProductGetProductList.Unmarshal(m, b)
}
func (m *RequestProductGetProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestProductGetProductList.Marshal(b, m, deterministic)
}
func (m *RequestProductGetProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestProductGetProductList.Merge(m, src)
}
func (m *RequestProductGetProductList) XXX_Size() int {
	return xxx_messageInfo_RequestProductGetProductList.Size(m)
}
func (m *RequestProductGetProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestProductGetProductList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestProductGetProductList proto.InternalMessageInfo

func (m *RequestProductGetProductList) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestProductGetProductList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestProductGetProductList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 返回客户端
type ResponseProductGetProductList struct {
	Base                 *Response        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProductList          []*SimpleProduct `protobuf:"bytes,2,rep,name=productList,proto3" json:"productList,omitempty"`
	TotalPage            int32            `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResponseProductGetProductList) Reset()         { *m = ResponseProductGetProductList{} }
func (m *ResponseProductGetProductList) String() string { return proto.CompactTextString(m) }
func (*ResponseProductGetProductList) ProtoMessage()    {}
func (*ResponseProductGetProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{12}
}

func (m *ResponseProductGetProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseProductGetProductList.Unmarshal(m, b)
}
func (m *ResponseProductGetProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseProductGetProductList.Marshal(b, m, deterministic)
}
func (m *ResponseProductGetProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseProductGetProductList.Merge(m, src)
}
func (m *ResponseProductGetProductList) XXX_Size() int {
	return xxx_messageInfo_ResponseProductGetProductList.Size(m)
}
func (m *ResponseProductGetProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseProductGetProductList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseProductGetProductList proto.InternalMessageInfo

func (m *ResponseProductGetProductList) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseProductGetProductList) GetProductList() []*SimpleProduct {
	if m != nil {
		return m.ProductList
	}
	return nil
}

func (m *ResponseProductGetProductList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

//@desc 获取商品详情
//@class Product
//@method GetProductInfo
//请求服务端
type RequestProductGetProductInfo struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProductId            int32    `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestProductGetProductInfo) Reset()         { *m = RequestProductGetProductInfo{} }
func (m *RequestProductGetProductInfo) String() string { return proto.CompactTextString(m) }
func (*RequestProductGetProductInfo) ProtoMessage()    {}
func (*RequestProductGetProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{13}
}

func (m *RequestProductGetProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestProductGetProductInfo.Unmarshal(m, b)
}
func (m *RequestProductGetProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestProductGetProductInfo.Marshal(b, m, deterministic)
}
func (m *RequestProductGetProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestProductGetProductInfo.Merge(m, src)
}
func (m *RequestProductGetProductInfo) XXX_Size() int {
	return xxx_messageInfo_RequestProductGetProductInfo.Size(m)
}
func (m *RequestProductGetProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestProductGetProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestProductGetProductInfo proto.InternalMessageInfo

func (m *RequestProductGetProductInfo) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestProductGetProductInfo) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

// 返回客户端
type ResponseProductGetProductInfo struct {
	Base                 *Response         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Product              *Product          `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	CommentList          []*ProductComment `protobuf:"bytes,3,rep,name=commentList,proto3" json:"commentList,omitempty"`
	CommentTotalPage     int32             `protobuf:"varint,4,opt,name=commentTotalPage,proto3" json:"commentTotalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseProductGetProductInfo) Reset()         { *m = ResponseProductGetProductInfo{} }
func (m *ResponseProductGetProductInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseProductGetProductInfo) ProtoMessage()    {}
func (*ResponseProductGetProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{14}
}

func (m *ResponseProductGetProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseProductGetProductInfo.Unmarshal(m, b)
}
func (m *ResponseProductGetProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseProductGetProductInfo.Marshal(b, m, deterministic)
}
func (m *ResponseProductGetProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseProductGetProductInfo.Merge(m, src)
}
func (m *ResponseProductGetProductInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseProductGetProductInfo.Size(m)
}
func (m *ResponseProductGetProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseProductGetProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseProductGetProductInfo proto.InternalMessageInfo

func (m *ResponseProductGetProductInfo) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseProductGetProductInfo) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ResponseProductGetProductInfo) GetCommentList() []*ProductComment {
	if m != nil {
		return m.CommentList
	}
	return nil
}

func (m *ResponseProductGetProductInfo) GetCommentTotalPage() int32 {
	if m != nil {
		return m.CommentTotalPage
	}
	return 0
}

//@desc 获取商品评价
//@class Product
//@method GetCommentList
//请求服务端
type RequestProductGetCommentList struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProductId            int32    `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestProductGetCommentList) Reset()         { *m = RequestProductGetCommentList{} }
func (m *RequestProductGetCommentList) String() string { return proto.CompactTextString(m) }
func (*RequestProductGetCommentList) ProtoMessage()    {}
func (*RequestProductGetCommentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{15}
}

func (m *RequestProductGetCommentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestProductGetCommentList.Unmarshal(m, b)
}
func (m *RequestProductGetCommentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestProductGetCommentList.Marshal(b, m, deterministic)
}
func (m *RequestProductGetCommentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestProductGetCommentList.Merge(m, src)
}
func (m *RequestProductGetCommentList) XXX_Size() int {
	return xxx_messageInfo_RequestProductGetCommentList.Size(m)
}
func (m *RequestProductGetCommentList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestProductGetCommentList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestProductGetCommentList proto.InternalMessageInfo

func (m *RequestProductGetCommentList) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestProductGetCommentList) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *RequestProductGetCommentList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestProductGetCommentList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 返回客户端
type ResponseProductGetCommentList struct {
	Base                 *Response         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CommentList          []*ProductComment `protobuf:"bytes,2,rep,name=commentList,proto3" json:"commentList,omitempty"`
	TotalPage            int32             `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseProductGetCommentList) Reset()         { *m = ResponseProductGetCommentList{} }
func (m *ResponseProductGetCommentList) String() string { return proto.CompactTextString(m) }
func (*ResponseProductGetCommentList) ProtoMessage()    {}
func (*ResponseProductGetCommentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{16}
}

func (m *ResponseProductGetCommentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseProductGetCommentList.Unmarshal(m, b)
}
func (m *ResponseProductGetCommentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseProductGetCommentList.Marshal(b, m, deterministic)
}
func (m *ResponseProductGetCommentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseProductGetCommentList.Merge(m, src)
}
func (m *ResponseProductGetCommentList) XXX_Size() int {
	return xxx_messageInfo_ResponseProductGetCommentList.Size(m)
}
func (m *ResponseProductGetCommentList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseProductGetCommentList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseProductGetCommentList proto.InternalMessageInfo

func (m *ResponseProductGetCommentList) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseProductGetCommentList) GetCommentList() []*ProductComment {
	if m != nil {
		return m.CommentList
	}
	return nil
}

func (m *ResponseProductGetCommentList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

//城市
type City struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int32        `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	AreaCode             string       `protobuf:"bytes,3,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NamePinyin           string       `protobuf:"bytes,5,opt,name=namePinyin,proto3" json:"namePinyin,omitempty"`
	ShortName            string       `protobuf:"bytes,6,opt,name=shortName,proto3" json:"shortName,omitempty"`
	ZipCode              string       `protobuf:"bytes,7,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	Lng                  float32      `protobuf:"fixed32,8,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  float32      `protobuf:"fixed32,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Type                 SignCityType `protobuf:"varint,10,opt,name=type,proto3,enum=BiuRpc.AppApi.SignCityType" json:"type,omitempty"`
	CreateTime           int32        `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{17}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *City) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *City) GetNamePinyin() string {
	if m != nil {
		return m.NamePinyin
	}
	return ""
}

func (m *City) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *City) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *City) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *City) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *City) GetType() SignCityType {
	if m != nil {
		return m.Type
	}
	return SignCityType_CITY_TYPE_NONE
}

func (m *City) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

//地址
type UserAddress struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Province             *City    `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City                 *City    `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District             *City    `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	Street               string   `protobuf:"bytes,7,opt,name=street,proto3" json:"street,omitempty"`
	IsDefault            bool     `protobuf:"varint,8,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddress) Reset()         { *m = UserAddress{} }
func (m *UserAddress) String() string { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()    {}
func (*UserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{18}
}

func (m *UserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddress.Unmarshal(m, b)
}
func (m *UserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddress.Marshal(b, m, deterministic)
}
func (m *UserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddress.Merge(m, src)
}
func (m *UserAddress) XXX_Size() int {
	return xxx_messageInfo_UserAddress.Size(m)
}
func (m *UserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddress proto.InternalMessageInfo

func (m *UserAddress) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserAddress) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *UserAddress) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserAddress) GetProvince() *City {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *UserAddress) GetCity() *City {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *UserAddress) GetDistrict() *City {
	if m != nil {
		return m.District
	}
	return nil
}

func (m *UserAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *UserAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

//@desc 获取收货地址列表
//@class Address
//@method GetUserAddressList
//请求服务端
type RequestAddressGetUserAddressList struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddressGetUserAddressList) Reset()         { *m = RequestAddressGetUserAddressList{} }
func (m *RequestAddressGetUserAddressList) String() string { return proto.CompactTextString(m) }
func (*RequestAddressGetUserAddressList) ProtoMessage()    {}
func (*RequestAddressGetUserAddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{19}
}

func (m *RequestAddressGetUserAddressList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddressGetUserAddressList.Unmarshal(m, b)
}
func (m *RequestAddressGetUserAddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddressGetUserAddressList.Marshal(b, m, deterministic)
}
func (m *RequestAddressGetUserAddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddressGetUserAddressList.Merge(m, src)
}
func (m *RequestAddressGetUserAddressList) XXX_Size() int {
	return xxx_messageInfo_RequestAddressGetUserAddressList.Size(m)
}
func (m *RequestAddressGetUserAddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddressGetUserAddressList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddressGetUserAddressList proto.InternalMessageInfo

func (m *RequestAddressGetUserAddressList) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestAddressGetUserAddressList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestAddressGetUserAddressList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 返回客户端
type ResponseAddressGetUserAddressList struct {
	Base                 *Response      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AddressList          []*UserAddress `protobuf:"bytes,2,rep,name=addressList,proto3" json:"addressList,omitempty"`
	TotalPage            int32          `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseAddressGetUserAddressList) Reset()         { *m = ResponseAddressGetUserAddressList{} }
func (m *ResponseAddressGetUserAddressList) String() string { return proto.CompactTextString(m) }
func (*ResponseAddressGetUserAddressList) ProtoMessage()    {}
func (*ResponseAddressGetUserAddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{20}
}

func (m *ResponseAddressGetUserAddressList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddressGetUserAddressList.Unmarshal(m, b)
}
func (m *ResponseAddressGetUserAddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddressGetUserAddressList.Marshal(b, m, deterministic)
}
func (m *ResponseAddressGetUserAddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddressGetUserAddressList.Merge(m, src)
}
func (m *ResponseAddressGetUserAddressList) XXX_Size() int {
	return xxx_messageInfo_ResponseAddressGetUserAddressList.Size(m)
}
func (m *ResponseAddressGetUserAddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddressGetUserAddressList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddressGetUserAddressList proto.InternalMessageInfo

func (m *ResponseAddressGetUserAddressList) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseAddressGetUserAddressList) GetAddressList() []*UserAddress {
	if m != nil {
		return m.AddressList
	}
	return nil
}

func (m *ResponseAddressGetUserAddressList) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

//@desc 获取收货地址详情
//@class Address
//@method GetUserAddressInfo
//请求服务端
type RequestAddressGetUserAddressInfo struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AddressId            int32    `protobuf:"varint,2,opt,name=addressId,proto3" json:"addressId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddressGetUserAddressInfo) Reset()         { *m = RequestAddressGetUserAddressInfo{} }
func (m *RequestAddressGetUserAddressInfo) String() string { return proto.CompactTextString(m) }
func (*RequestAddressGetUserAddressInfo) ProtoMessage()    {}
func (*RequestAddressGetUserAddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{21}
}

func (m *RequestAddressGetUserAddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddressGetUserAddressInfo.Unmarshal(m, b)
}
func (m *RequestAddressGetUserAddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddressGetUserAddressInfo.Marshal(b, m, deterministic)
}
func (m *RequestAddressGetUserAddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddressGetUserAddressInfo.Merge(m, src)
}
func (m *RequestAddressGetUserAddressInfo) XXX_Size() int {
	return xxx_messageInfo_RequestAddressGetUserAddressInfo.Size(m)
}
func (m *RequestAddressGetUserAddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddressGetUserAddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddressGetUserAddressInfo proto.InternalMessageInfo

func (m *RequestAddressGetUserAddressInfo) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestAddressGetUserAddressInfo) GetAddressId() int32 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

// 返回客户端
type ResponseAddressGetUserAddressInfo struct {
	Base                 *Response    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AddressInfo          *UserAddress `protobuf:"bytes,2,opt,name=addressInfo,proto3" json:"addressInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResponseAddressGetUserAddressInfo) Reset()         { *m = ResponseAddressGetUserAddressInfo{} }
func (m *ResponseAddressGetUserAddressInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseAddressGetUserAddressInfo) ProtoMessage()    {}
func (*ResponseAddressGetUserAddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{22}
}

func (m *ResponseAddressGetUserAddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddressGetUserAddressInfo.Unmarshal(m, b)
}
func (m *ResponseAddressGetUserAddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddressGetUserAddressInfo.Marshal(b, m, deterministic)
}
func (m *ResponseAddressGetUserAddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddressGetUserAddressInfo.Merge(m, src)
}
func (m *ResponseAddressGetUserAddressInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseAddressGetUserAddressInfo.Size(m)
}
func (m *ResponseAddressGetUserAddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddressGetUserAddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddressGetUserAddressInfo proto.InternalMessageInfo

func (m *ResponseAddressGetUserAddressInfo) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ResponseAddressGetUserAddressInfo) GetAddressInfo() *UserAddress {
	if m != nil {
		return m.AddressInfo
	}
	return nil
}

//@desc 添加收货地址
//@class Address
//@method AddUserAddress
//请求服务端
type RequestAddressAddUserAddress struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Receiver             string   `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ProvinceId           int32    `protobuf:"varint,4,opt,name=provinceId,proto3" json:"provinceId,omitempty"`
	City                 int32    `protobuf:"varint,5,opt,name=city,proto3" json:"city,omitempty"`
	District             int32    `protobuf:"varint,6,opt,name=district,proto3" json:"district,omitempty"`
	Street               string   `protobuf:"bytes,7,opt,name=street,proto3" json:"street,omitempty"`
	IsDefault            bool     `protobuf:"varint,8,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddressAddUserAddress) Reset()         { *m = RequestAddressAddUserAddress{} }
func (m *RequestAddressAddUserAddress) String() string { return proto.CompactTextString(m) }
func (*RequestAddressAddUserAddress) ProtoMessage()    {}
func (*RequestAddressAddUserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{23}
}

func (m *RequestAddressAddUserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddressAddUserAddress.Unmarshal(m, b)
}
func (m *RequestAddressAddUserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddressAddUserAddress.Marshal(b, m, deterministic)
}
func (m *RequestAddressAddUserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddressAddUserAddress.Merge(m, src)
}
func (m *RequestAddressAddUserAddress) XXX_Size() int {
	return xxx_messageInfo_RequestAddressAddUserAddress.Size(m)
}
func (m *RequestAddressAddUserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddressAddUserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddressAddUserAddress proto.InternalMessageInfo

func (m *RequestAddressAddUserAddress) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestAddressAddUserAddress) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *RequestAddressAddUserAddress) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RequestAddressAddUserAddress) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *RequestAddressAddUserAddress) GetCity() int32 {
	if m != nil {
		return m.City
	}
	return 0
}

func (m *RequestAddressAddUserAddress) GetDistrict() int32 {
	if m != nil {
		return m.District
	}
	return 0
}

func (m *RequestAddressAddUserAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *RequestAddressAddUserAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

// 返回客户端
type ResponseAddressAddUserAddress struct {
	Base                 *Response `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseAddressAddUserAddress) Reset()         { *m = ResponseAddressAddUserAddress{} }
func (m *ResponseAddressAddUserAddress) String() string { return proto.CompactTextString(m) }
func (*ResponseAddressAddUserAddress) ProtoMessage()    {}
func (*ResponseAddressAddUserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{24}
}

func (m *ResponseAddressAddUserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddressAddUserAddress.Unmarshal(m, b)
}
func (m *ResponseAddressAddUserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddressAddUserAddress.Marshal(b, m, deterministic)
}
func (m *ResponseAddressAddUserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddressAddUserAddress.Merge(m, src)
}
func (m *ResponseAddressAddUserAddress) XXX_Size() int {
	return xxx_messageInfo_ResponseAddressAddUserAddress.Size(m)
}
func (m *ResponseAddressAddUserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddressAddUserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddressAddUserAddress proto.InternalMessageInfo

func (m *ResponseAddressAddUserAddress) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

//@desc 修改收货地址
//@class Address
//@method UpdateUserAddress
//请求服务端
type RequestAddressUpdateUserAddress struct {
	Base                 *Request `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Dreceiver            string   `protobuf:"bytes,2,opt,name=dreceiver,proto3" json:"dreceiver,omitempty"`
	IsUpdateReceiver     bool     `protobuf:"varint,3,opt,name=isUpdateReceiver,proto3" json:"isUpdateReceiver,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	IsUpdateMobile       bool     `protobuf:"varint,5,opt,name=isUpdateMobile,proto3" json:"isUpdateMobile,omitempty"`
	ProvinceId           int32    `protobuf:"varint,6,opt,name=provinceId,proto3" json:"provinceId,omitempty"`
	IsUpdateProvinceId   bool     `protobuf:"varint,7,opt,name=isUpdateProvinceId,proto3" json:"isUpdateProvinceId,omitempty"`
	City                 int32    `protobuf:"varint,8,opt,name=city,proto3" json:"city,omitempty"`
	IsUpdateCity         bool     `protobuf:"varint,9,opt,name=isUpdateCity,proto3" json:"isUpdateCity,omitempty"`
	District             int32    `protobuf:"varint,10,opt,name=district,proto3" json:"district,omitempty"`
	IsUpdateDistrict     bool     `protobuf:"varint,11,opt,name=isUpdateDistrict,proto3" json:"isUpdateDistrict,omitempty"`
	Street               string   `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	IsUpdateStreet       bool     `protobuf:"varint,13,opt,name=isUpdateStreet,proto3" json:"isUpdateStreet,omitempty"`
	IsDefault            bool     `protobuf:"varint,14,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	IsUpdateIsDefault    bool     `protobuf:"varint,15,opt,name=isUpdateIsDefault,proto3" json:"isUpdateIsDefault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddressUpdateUserAddress) Reset()         { *m = RequestAddressUpdateUserAddress{} }
func (m *RequestAddressUpdateUserAddress) String() string { return proto.CompactTextString(m) }
func (*RequestAddressUpdateUserAddress) ProtoMessage()    {}
func (*RequestAddressUpdateUserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{25}
}

func (m *RequestAddressUpdateUserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddressUpdateUserAddress.Unmarshal(m, b)
}
func (m *RequestAddressUpdateUserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddressUpdateUserAddress.Marshal(b, m, deterministic)
}
func (m *RequestAddressUpdateUserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddressUpdateUserAddress.Merge(m, src)
}
func (m *RequestAddressUpdateUserAddress) XXX_Size() int {
	return xxx_messageInfo_RequestAddressUpdateUserAddress.Size(m)
}
func (m *RequestAddressUpdateUserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddressUpdateUserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddressUpdateUserAddress proto.InternalMessageInfo

func (m *RequestAddressUpdateUserAddress) GetBase() *Request {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RequestAddressUpdateUserAddress) GetDreceiver() string {
	if m != nil {
		return m.Dreceiver
	}
	return ""
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateReceiver() bool {
	if m != nil {
		return m.IsUpdateReceiver
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateMobile() bool {
	if m != nil {
		return m.IsUpdateMobile
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetProvinceId() int32 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateProvinceId() bool {
	if m != nil {
		return m.IsUpdateProvinceId
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetCity() int32 {
	if m != nil {
		return m.City
	}
	return 0
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateCity() bool {
	if m != nil {
		return m.IsUpdateCity
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetDistrict() int32 {
	if m != nil {
		return m.District
	}
	return 0
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateDistrict() bool {
	if m != nil {
		return m.IsUpdateDistrict
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateStreet() bool {
	if m != nil {
		return m.IsUpdateStreet
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *RequestAddressUpdateUserAddress) GetIsUpdateIsDefault() bool {
	if m != nil {
		return m.IsUpdateIsDefault
	}
	return false
}

// 返回客户端
type ResponseAddressUpdateUserAddress struct {
	Base                 *Response `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseAddressUpdateUserAddress) Reset()         { *m = ResponseAddressUpdateUserAddress{} }
func (m *ResponseAddressUpdateUserAddress) String() string { return proto.CompactTextString(m) }
func (*ResponseAddressUpdateUserAddress) ProtoMessage()    {}
func (*ResponseAddressUpdateUserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f47142efccb15f67, []int{26}
}

func (m *ResponseAddressUpdateUserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddressUpdateUserAddress.Unmarshal(m, b)
}
func (m *ResponseAddressUpdateUserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddressUpdateUserAddress.Marshal(b, m, deterministic)
}
func (m *ResponseAddressUpdateUserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddressUpdateUserAddress.Merge(m, src)
}
func (m *ResponseAddressUpdateUserAddress) XXX_Size() int {
	return xxx_messageInfo_ResponseAddressUpdateUserAddress.Size(m)
}
func (m *ResponseAddressUpdateUserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddressUpdateUserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddressUpdateUserAddress proto.InternalMessageInfo

func (m *ResponseAddressUpdateUserAddress) GetBase() *Response {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterEnum("BiuRpc.AppApi.SignCityType", SignCityType_name, SignCityType_value)
	proto.RegisterType((*Banner)(nil), "BiuRpc.AppApi.Banner")
	proto.RegisterType((*RequestHomeGetHomeInfo)(nil), "BiuRpc.AppApi.RequestHomeGetHomeInfo")
	proto.RegisterType((*ResponseHomeGetHomeInfo)(nil), "BiuRpc.AppApi.ResponseHomeGetHomeInfo")
	proto.RegisterType((*RequestHomeGetRecommendProductList)(nil), "BiuRpc.AppApi.RequestHomeGetRecommendProductList")
	proto.RegisterType((*ResponseHomeGetRecommendProductList)(nil), "BiuRpc.AppApi.ResponseHomeGetRecommendProductList")
	proto.RegisterType((*SimpleProduct)(nil), "BiuRpc.AppApi.SimpleProduct")
	proto.RegisterType((*Product)(nil), "BiuRpc.AppApi.Product")
	proto.RegisterType((*ProductComment)(nil), "BiuRpc.AppApi.ProductComment")
	proto.RegisterType((*Category)(nil), "BiuRpc.AppApi.Category")
	proto.RegisterType((*RequestProductGetCategoryList)(nil), "BiuRpc.AppApi.RequestProductGetCategoryList")
	proto.RegisterType((*ResponseProductGetCategoryList)(nil), "BiuRpc.AppApi.ResponseProductGetCategoryList")
	proto.RegisterType((*RequestProductGetProductList)(nil), "BiuRpc.AppApi.RequestProductGetProductList")
	proto.RegisterType((*ResponseProductGetProductList)(nil), "BiuRpc.AppApi.ResponseProductGetProductList")
	proto.RegisterType((*RequestProductGetProductInfo)(nil), "BiuRpc.AppApi.RequestProductGetProductInfo")
	proto.RegisterType((*ResponseProductGetProductInfo)(nil), "BiuRpc.AppApi.ResponseProductGetProductInfo")
	proto.RegisterType((*RequestProductGetCommentList)(nil), "BiuRpc.AppApi.RequestProductGetCommentList")
	proto.RegisterType((*ResponseProductGetCommentList)(nil), "BiuRpc.AppApi.ResponseProductGetCommentList")
	proto.RegisterType((*City)(nil), "BiuRpc.AppApi.City")
	proto.RegisterType((*UserAddress)(nil), "BiuRpc.AppApi.UserAddress")
	proto.RegisterType((*RequestAddressGetUserAddressList)(nil), "BiuRpc.AppApi.RequestAddressGetUserAddressList")
	proto.RegisterType((*ResponseAddressGetUserAddressList)(nil), "BiuRpc.AppApi.ResponseAddressGetUserAddressList")
	proto.RegisterType((*RequestAddressGetUserAddressInfo)(nil), "BiuRpc.AppApi.RequestAddressGetUserAddressInfo")
	proto.RegisterType((*ResponseAddressGetUserAddressInfo)(nil), "BiuRpc.AppApi.ResponseAddressGetUserAddressInfo")
	proto.RegisterType((*RequestAddressAddUserAddress)(nil), "BiuRpc.AppApi.RequestAddressAddUserAddress")
	proto.RegisterType((*ResponseAddressAddUserAddress)(nil), "BiuRpc.AppApi.ResponseAddressAddUserAddress")
	proto.RegisterType((*RequestAddressUpdateUserAddress)(nil), "BiuRpc.AppApi.RequestAddressUpdateUserAddress")
	proto.RegisterType((*ResponseAddressUpdateUserAddress)(nil), "BiuRpc.AppApi.ResponseAddressUpdateUserAddress")
}

func init() {
	proto.RegisterFile("app_api.proto", fileDescriptor_f47142efccb15f67)
}

var fileDescriptor_f47142efccb15f67 = []byte{
	// 1227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0xff, 0xdb, 0x89, 0x9b, 0xe4, 0xa4, 0xcd, 0x3f, 0x0c, 0xa5, 0x8d, 0x4a, 0xb7, 0x04, 0x23,
	0x41, 0x28, 0xa8, 0x8b, 0x8a, 0xb8, 0x02, 0x81, 0xda, 0xb4, 0x2a, 0x41, 0x6c, 0x37, 0x9a, 0x66,
	0x91, 0xf6, 0xaa, 0x72, 0xed, 0x69, 0x19, 0x94, 0xd8, 0x5e, 0x7b, 0x12, 0xc8, 0x82, 0xb8, 0xe0,
	0x06, 0x2e, 0xb8, 0xe2, 0x82, 0x37, 0x40, 0x02, 0x2e, 0x90, 0x78, 0x1a, 0x9e, 0x81, 0xb7, 0x40,
	0x33, 0x1e, 0x7f, 0x8d, 0x93, 0x6e, 0xbc, 0xc0, 0x8a, 0xab, 0x78, 0xce, 0xfc, 0xce, 0x39, 0x73,
	0x7e, 0xe7, 0xab, 0x2a, 0x6c, 0x58, 0xbe, 0x7f, 0x69, 0xf9, 0xf4, 0xc0, 0x0f, 0x3c, 0xe6, 0xa1,
	0x8d, 0x63, 0x3a, 0xc5, 0xbe, 0x7d, 0x70, 0xe4, 0xfb, 0x47, 0x3e, 0xdd, 0x81, 0x2b, 0x2b, 0x24,
	0xd1, 0x95, 0x89, 0x61, 0xed, 0xd8, 0x72, 0x5d, 0x12, 0xa0, 0x16, 0xe8, 0xd4, 0xe9, 0x68, 0x5d,
	0xad, 0x67, 0x60, 0x9d, 0x3a, 0x68, 0x13, 0x0c, 0x46, 0xd9, 0x98, 0x74, 0xf4, 0xae, 0xd6, 0x6b,
	0xe0, 0xe8, 0x80, 0x4c, 0xa8, 0xb8, 0xd6, 0xac, 0x53, 0xe9, 0x6a, 0xbd, 0xe6, 0x61, 0xfb, 0x40,
	0x1a, 0x3e, 0xe6, 0x06, 0xcf, 0xad, 0x19, 0xe6, 0x97, 0xe6, 0x31, 0x6c, 0x61, 0xf2, 0x68, 0x4a,
	0x42, 0xf6, 0xa1, 0x37, 0x21, 0x67, 0x44, 0xfc, 0x0c, 0xdc, 0x6b, 0x0f, 0xf5, 0xa0, 0xca, 0x7d,
	0x0b, 0x2f, 0xcd, 0xc3, 0xcd, 0x9c, 0xba, 0x54, 0xc1, 0x02, 0x61, 0x7e, 0x09, 0xdb, 0x98, 0x84,
	0xbe, 0xe7, 0x86, 0x44, 0x35, 0xf2, 0x7a, 0xce, 0xc8, 0x0b, 0x8a, 0x91, 0x48, 0x27, 0xb2, 0x82,
	0xde, 0x01, 0xb8, 0x12, 0xd1, 0x7d, 0x4c, 0x43, 0xd6, 0xd1, 0xbb, 0x95, 0xac, 0x42, 0xc4, 0xc6,
	0x41, 0x14, 0x3e, 0xce, 0x00, 0xcd, 0xaf, 0xc1, 0xcc, 0x07, 0x80, 0x89, 0xed, 0x4d, 0x26, 0xc4,
	0x75, 0x86, 0x81, 0xe7, 0x4c, 0x6d, 0xc6, 0x51, 0xab, 0x07, 0x83, 0x10, 0x54, 0x7d, 0xeb, 0x26,
	0x62, 0xd2, 0xc0, 0xe2, 0x1b, 0xed, 0x40, 0x9d, 0xff, 0x5e, 0xd0, 0xc7, 0x44, 0xb0, 0x69, 0xe0,
	0xe4, 0x6c, 0xfe, 0xa6, 0xc1, 0x2b, 0x4a, 0xf4, 0x0b, 0x5f, 0x50, 0x82, 0x89, 0xf7, 0xa1, 0xe9,
	0xa7, 0x9a, 0x92, 0x8a, 0x5d, 0x85, 0x8a, 0x0b, 0x3a, 0xf1, 0xc7, 0x44, 0x7a, 0xc0, 0x59, 0x05,
	0xb4, 0x0b, 0x0d, 0xe6, 0x31, 0x6b, 0x3c, 0xe4, 0x71, 0x44, 0xef, 0x4d, 0x05, 0xe6, 0xe7, 0xb0,
	0x91, 0xd3, 0x5d, 0xb1, 0x98, 0xf6, 0xc1, 0xb0, 0xbd, 0x19, 0x09, 0x64, 0x39, 0xe5, 0x29, 0x1c,
	0x52, 0x9b, 0x4d, 0x03, 0x82, 0x23, 0x08, 0xb7, 0xe0, 0x07, 0xd4, 0x26, 0x9d, 0x6a, 0x57, 0xeb,
	0xe9, 0x38, 0x3a, 0x98, 0x8f, 0xa0, 0xf6, 0xac, 0x5d, 0x7e, 0xab, 0x41, 0x4b, 0xfa, 0xec, 0x8b,
	0x94, 0x14, 0x5d, 0xbf, 0x01, 0xd5, 0x69, 0x48, 0x02, 0xe1, 0xb9, 0x79, 0xb8, 0x9d, 0xf3, 0x11,
	0xf1, 0xf4, 0x20, 0x24, 0x01, 0x16, 0x20, 0xd4, 0x81, 0x9a, 0xed, 0xb9, 0x8c, 0xb8, 0x4c, 0xbc,
	0xa9, 0x81, 0xe3, 0x23, 0xda, 0x03, 0xb0, 0x03, 0x62, 0x31, 0x32, 0xa2, 0x93, 0xe8, 0x11, 0x06,
	0xce, 0x48, 0xcc, 0x3f, 0x34, 0xa8, 0xf7, 0x2d, 0x46, 0x6e, 0xbc, 0x60, 0xbe, 0x62, 0xf8, 0x9b,
	0x60, 0x8c, 0xc9, 0x8c, 0x8c, 0x65, 0x0a, 0xa3, 0x03, 0xaf, 0xcf, 0xd0, 0x0b, 0x98, 0x74, 0x21,
	0xbe, 0x15, 0xe7, 0x86, 0xea, 0x9c, 0xdf, 0x4f, 0x7d, 0x27, 0xbe, 0x5f, 0x8b, 0xee, 0x53, 0x09,
	0x7a, 0x17, 0xd6, 0x6d, 0xf9, 0x36, 0x51, 0x71, 0x35, 0x51, 0x71, 0xdb, 0x4a, 0xc5, 0xc5, 0xcf,
	0xc7, 0x39, 0xb0, 0x39, 0x80, 0x3b, 0xb2, 0x83, 0x24, 0xd3, 0x67, 0x84, 0xf5, 0x33, 0x80, 0x12,
	0x83, 0xe4, 0x3b, 0x0d, 0xf6, 0xe2, 0x5e, 0x58, 0x62, 0xac, 0x44, 0x1b, 0xa9, 0x51, 0xe9, 0x65,
	0xa2, 0xfa, 0x02, 0x76, 0x0b, 0x51, 0x3d, 0x9b, 0x81, 0xf2, 0xb3, 0xc6, 0x09, 0x55, 0x49, 0xf8,
	0x4f, 0x8e, 0x92, 0xeb, 0xe5, 0x24, 0x95, 0x5b, 0x21, 0xdc, 0x8f, 0x74, 0x3b, 0x70, 0x24, 0x53,
	0xa9, 0xc0, 0xfc, 0xf3, 0x36, 0x4a, 0xca, 0xee, 0x99, 0xb7, 0xa0, 0x26, 0x2d, 0xcb, 0x9e, 0xdf,
	0x52, 0xe8, 0x88, 0x89, 0x88, 0x61, 0xe8, 0x03, 0x68, 0x46, 0x03, 0x3d, 0x22, 0xb1, 0x22, 0x48,
	0xbc, 0xb3, 0x58, 0x4b, 0x8e, 0x19, 0x9c, 0xd5, 0x40, 0xfb, 0xd0, 0x96, 0xc7, 0x51, 0x42, 0x66,
	0xd4, 0xbf, 0x05, 0xb9, 0xf9, 0xa3, 0xb6, 0x80, 0xd4, 0x7e, 0xc6, 0xd8, 0x3f, 0x44, 0x6a, 0x52,
	0x97, 0x95, 0x25, 0x75, 0x59, 0x55, 0xea, 0xf2, 0x97, 0x85, 0x49, 0xc8, 0xbe, 0xac, 0x44, 0x12,
	0x14, 0x4a, 0xf5, 0xd2, 0x94, 0xde, 0x5e, 0x98, 0x3f, 0xe9, 0x50, 0xed, 0x53, 0x56, 0x9c, 0xb4,
	0x6d, 0xa8, 0xf8, 0x34, 0x26, 0x83, 0x7f, 0xf2, 0x90, 0xad, 0x80, 0x58, 0x7d, 0xcf, 0x21, 0x72,
	0xa6, 0x27, 0x67, 0x4e, 0x91, 0x6b, 0xc9, 0x71, 0xde, 0xc0, 0xe2, 0x9b, 0xcf, 0x52, 0xfe, 0x3b,
	0xa4, 0xee, 0x9c, 0xba, 0x62, 0xd6, 0x36, 0x70, 0x46, 0xc2, 0x1f, 0x16, 0x7e, 0xea, 0x05, 0xec,
	0xdc, 0x92, 0xa3, 0xb6, 0x81, 0x53, 0x01, 0x5f, 0x20, 0x8f, 0xa9, 0x2f, 0x9c, 0xd5, 0xa2, 0x05,
	0x22, 0x8f, 0xfc, 0x65, 0x63, 0xf7, 0xa6, 0x53, 0x17, 0xeb, 0x8b, 0x7f, 0x0a, 0x89, 0xc5, 0x3a,
	0x0d, 0x29, 0xb1, 0x18, 0xba, 0x0b, 0x55, 0x36, 0xf7, 0x49, 0x07, 0xba, 0x5a, 0xaf, 0x75, 0xf8,
	0x62, 0xa1, 0x8d, 0x6f, 0x5c, 0x1e, 0xf4, 0x68, 0xee, 0x13, 0x2c, 0x80, 0xca, 0x62, 0x68, 0x16,
	0xb6, 0xd2, 0x0f, 0x3a, 0x34, 0xf9, 0x7a, 0x3b, 0x72, 0x9c, 0x80, 0x84, 0x61, 0x81, 0xae, 0x1d,
	0xa8, 0x07, 0xc4, 0x26, 0x74, 0x26, 0x17, 0x64, 0x03, 0x27, 0x67, 0xb4, 0x05, 0x6b, 0x13, 0xef,
	0x8a, 0x8e, 0x63, 0xda, 0xe4, 0x09, 0xdd, 0x85, 0xba, 0x1f, 0x78, 0x33, 0xea, 0xca, 0x65, 0xdc,
	0x3c, 0x7c, 0x5e, 0x1d, 0xb9, 0x94, 0xcd, 0x71, 0x02, 0x42, 0xaf, 0x41, 0xd5, 0xa6, 0x6c, 0x2e,
	0xb8, 0x5c, 0x02, 0x16, 0x00, 0x6e, 0xd9, 0xa1, 0x21, 0x0b, 0xa8, 0xcd, 0x04, 0xb3, 0xcb, 0x2c,
	0xc7, 0x20, 0xfe, 0xc4, 0x90, 0x05, 0x84, 0x30, 0x49, 0xb6, 0x3c, 0xf1, 0x1c, 0xd1, 0xf0, 0x84,
	0x5c, 0x5b, 0xd3, 0x31, 0x13, 0x8c, 0xd7, 0x71, 0x2a, 0x30, 0xbf, 0x82, 0xae, 0xec, 0x23, 0x49,
	0xcb, 0x19, 0x61, 0x19, 0x92, 0xfe, 0xe5, 0xf1, 0xff, 0xab, 0x06, 0x2f, 0xc7, 0xcd, 0xb2, 0xdc,
	0x7f, 0x89, 0x56, 0x7b, 0x0f, 0x9a, 0x56, 0xaa, 0x29, 0x5b, 0x6d, 0x47, 0x21, 0x2e, 0x63, 0x1f,
	0x67, 0xe1, 0x4f, 0xe8, 0xb3, 0xcf, 0x6e, 0xa7, 0xaa, 0xfc, 0x12, 0x90, 0xae, 0xd3, 0x79, 0x95,
	0x08, 0xcc, 0xef, 0x9f, 0x44, 0x4c, 0xd9, 0x45, 0x90, 0x12, 0xc3, 0x35, 0xe5, 0x32, 0x58, 0x85,
	0x18, 0x0e, 0x37, 0xbf, 0xd1, 0x93, 0x39, 0x2d, 0xef, 0x8f, 0x1c, 0x27, 0xdb, 0x4b, 0xab, 0xc7,
	0xfd, 0x34, 0x5d, 0xb6, 0x07, 0x10, 0x37, 0xd0, 0xc0, 0x89, 0xff, 0xde, 0x4c, 0x25, 0xbc, 0xec,
	0x92, 0xa6, 0x32, 0x64, 0xff, 0xec, 0x28, 0xfd, 0x63, 0xfc, 0xed, 0x56, 0xf9, 0x28, 0x5d, 0x09,
	0x8b, 0x49, 0x58, 0x3d, 0x1d, 0xe6, 0xef, 0x55, 0x78, 0x29, 0x4f, 0xe8, 0x03, 0xf1, 0x17, 0xea,
	0xd3, 0x71, 0xba, 0x0b, 0x0d, 0x47, 0x21, 0x35, 0x15, 0xf0, 0x85, 0x4c, 0xa5, 0x79, 0x1c, 0x83,
	0x2a, 0x22, 0xb8, 0x82, 0x3c, 0x93, 0x81, 0x6a, 0x2e, 0x03, 0xaf, 0x42, 0x2b, 0xc6, 0xde, 0x8b,
	0xee, 0x0d, 0x61, 0x41, 0x91, 0x2a, 0x99, 0x5a, 0x2b, 0x64, 0xea, 0x00, 0x50, 0xac, 0x31, 0x4c,
	0x71, 0x35, 0x61, 0x6b, 0xc1, 0x4d, 0x92, 0xd9, 0x7a, 0x26, 0xb3, 0x26, 0xac, 0xc7, 0x48, 0x3e,
	0x02, 0xc5, 0xce, 0xa8, 0xe3, 0x9c, 0x2c, 0x97, 0x7d, 0x50, 0xb2, 0x9f, 0xe1, 0xe3, 0x24, 0xc6,
	0x34, 0xf3, 0x7c, 0x9c, 0x14, 0x2b, 0x65, 0x3d, 0x57, 0x29, 0x19, 0x3e, 0x2e, 0xa2, 0xfb, 0x8d,
	0x3c, 0x1f, 0x17, 0x0b, 0x2a, 0xaa, 0xa5, 0x54, 0x14, 0x7a, 0x13, 0x9e, 0x8b, 0xf1, 0x83, 0x04,
	0xf5, 0x7f, 0x81, 0x2a, 0x5e, 0x98, 0xf7, 0xf8, 0xfc, 0xc9, 0xd5, 0x5f, 0xb1, 0x66, 0x56, 0x2f,
	0xc1, 0xfd, 0x6b, 0x58, 0xcf, 0x2e, 0x51, 0x84, 0xa0, 0xd5, 0x1f, 0x8c, 0x1e, 0x5e, 0x8e, 0x1e,
	0x0e, 0x4f, 0x2f, 0xcf, 0xef, 0x9f, 0x9f, 0xb6, 0xff, 0x87, 0xb6, 0x00, 0xa5, 0xb2, 0x21, 0xbe,
	0xff, 0xc9, 0xe0, 0xbc, 0x7f, 0xda, 0xd6, 0xf2, 0x58, 0xfe, 0xd5, 0xd6, 0xf3, 0xd8, 0x93, 0xc1,
	0xc5, 0x08, 0x0f, 0xfa, 0xa3, 0x76, 0xe5, 0x6a, 0x4d, 0xfc, 0x3f, 0xe7, 0xed, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x79, 0xe5, 0x1b, 0x11, 0xfb, 0x11, 0x00, 0x00,
}
