# 网关服务地址
gateway_url = "http://127.0.0.1:8000"

# 验签服务地址
auth_url = "http://127.0.0.1:8001"

# 许可服务 (鉴权子服务)地址

# 用户服务地址
user_url = "http://127.0.0.1:8002"

# 验证码服务地址
verification_code_url = "http://127.0.0.1:8003"

# 短信服务地址
sms_url = "http://127.0.0.1:8004"

# 日志服务
logger_url = "http://127.0.0.1:8005"

# 文件存储服务
file_url = "http://127.0.0.1:8006"
