app_name = "wordgame-go"
app_port = "8000"
hex_key = "1UgZfL<=Au3M9dQrcB7yzzd==8?xlZ:T3oP1id>jKWi4Bc9Kz<RbTSXqgPWJXxes945rzQ4ojlsqN25:95yb1-DsbAu1k6mUSs27CXDmQu-mx0lhH82-rA5=<NO0Z4:x"
is_auth = true
ignore_auth = ["/auth/getToken"]
is_login = true
ignore_login = ["/member/login"]
