# 基础
ERROR_UNAUTHOZED = "Unauthorized!"
ERROR_UNLOGIN = "用户未登录!"
ERROR_REQUEST_PARAMS = "参数错误!"

# 用户模块
ERROR_LOGIN_PASSWORD = "密码错误!"
ERROR_LOGIN_LOCKED = "用户不存在或者已经锁定!"
ERROR_LOGIN_MISSING = "未找到该用户数据!"
ERROR_USERNAME_EXISTS = "用户名已经存在!"
ERROR_EMAIL_EXISTS = "邮箱已经存在!"
ERROR_PHONE_EXISTS = "手机号已经存在!"

# Feign模块
ERROR_FEIGN_SERVICE_MISSING = "请求的服务不存在!"
ERROR_FEIGN_REQUEST_FAIL = "请求失败!"

# File模块
ERROR_FILE_EXISTS = "该资源已经存在!"
ERROR_FILE_ADD_FAIL = "资源入库失败!"
ERROR_FILE_UPDATE_FAIL = "资源信息更新失败!"
ERROR_FILE_MISSING = "未找到相关的资源文件!"
