# 基础
ERROR_UNAUTHOZED = "Unauthorized!"
ERROR_UNLOGIN = "用户未登录!"
ERROR_REQUEST_PARAMS = "参数错误!"

# 用户模块
ERROR_USER_LOGIN_PASSWORD = "密码错误!"
ERROR_USER_LOGIN_LOCKED = "用户不存在或者已经锁定!"
ERROR_USER_LOGIN_MISSING = "未找到该用户数据!"
ERROR_USER_USERNAME_EXISTS = "用户名已经存在!"
ERROR_USER_EMAIL_EXISTS = "邮箱已经存在!"
ERROR_USER_PHONE_EXISTS = "手机号已经存在!"
ERROR_USER_UPDATE_FAIL = "用户数据更新失败!"

# Feign模块
ERROR_FEIGN_SERVICE_MISSING = "请求的服务不存在!"
ERROR_FEIGN_REQUEST_FAIL = "请求失败!"

# File模块
ERROR_FILE_EXISTS = "该资源已经存在!"
ERROR_FILE_ADD_FAIL = "资源入库失败!"
ERROR_FILE_UPDATE_FAIL = "资源信息更新失败!"
ERROR_FILE_MISSING = "未找到相关的资源文件!"

# 验证码模块
ERROR_CAPTCHA_TIMEOUT = "验证码已过期!"
ERROR_CAPTCHA_FAIL = "验证码错误!"
